In [1]:
import pandas as pd
import numpy as np
from synth_pat.paths import Paths

In [2]:
for pid in ['sub-2015052501', 'sub-2015060902', 'sub-2019012101', 'sub-2015060401', 'sub-2015061901', 'sub-2019012402']:
    pid_idx = int(pid.split('sub-')[1])
    emp_data = pd.read_csv(f'{Paths.DATA}/ALL_daniela_full_extracted_features.csv', index_col = 'pid')
    synth_data = pd.read_csv(f'{Paths.RESULTS}/{pid}/{Paths.TYPE_OF_SWEEP}_extracted_features.csv', index_col = 0)
    print(f'Comparing {Paths.TYPE_OF_SWEEP}_extracted_features.csv for {pid}')
    params = ['ws', 'njdopa_ctx', 'njdopa_str']
    feat_cols = [col for col in synth_data.columns if col not in params]
    emp_data_pid = emp_data.loc[pid_idx, feat_cols]

    err_line = []
    for i in synth_data.index:
        line_feat = synth_data.loc[i,feat_cols]
        err_line.append(np.sum(np.abs(line_feat - emp_data_pid)))

    err_line = np.array(err_line)
    best_idx = np.argsort(err_line)[:100]
    best_params = synth_data.loc[best_idx, params]
    #best_params.to_csv(f'{Paths.DERIVATIVES}/{pid}/best_ppc_params_for_medication.csv', index=False)

Comparing huifang_ppc_sweep2_extracted_features.csv for sub-2015052501
Comparing huifang_ppc_sweep2_extracted_features.csv for sub-2015060902
Comparing huifang_ppc_sweep2_extracted_features.csv for sub-2019012101
Comparing huifang_ppc_sweep2_extracted_features.csv for sub-2015060401
Comparing huifang_ppc_sweep2_extracted_features.csv for sub-2015061901
Comparing huifang_ppc_sweep2_extracted_features.csv for sub-2019012402

In [3]:
best_params

         ws  njdopa_ctx  njdopa_str
423  0.3104      1.0022      0.2455
482  0.2536      0.5635      0.2496
0    0.2164      1.8656      0.2503
404  0.2336      0.8912      0.2856
449  0.2463      1.1043      0.2755
..      ...         ...         ...
248  0.2193      0.4008      0.2330
26   0.2599      1.1922      0.2437
469  0.2670      1.0704      0.2592
425  0.2065      0.7244      0.2990
387  0.2553      1.1850      0.2935

[100 rows x 3 columns]

In [4]:
synth_data

,GBC,VAR_FCD,ws,njdopa_ctx,njdopa_str,L.PU_FC,L.CA_FC,L.HI_FC,L.STG_FC,L.CER_FC,...,R.HI_ALFF,R.STG_ALFF,R.CER_ALFF,R.CACG_ALFF,R.RACG_ALFF,R.IN_ALFF,R.PCG_ALFF,R.POP_ALFF,R.POR_ALFF,R.PTR_ALFF
0,0.045576,0.002687,0.2164,1.8656,0.2503,0.012880,0.027508,0.055220,0.010900,0.013787,...,-0.588868,-1.160637,0.892146,-1.084259,-1.419866,-0.214034,-0.024485,0.227466,-0.669840,1.790258
1,0.054492,0.002449,0.2536,0.6534,0.2345,0.061544,0.045853,0.051125,0.043508,0.036525,...,-0.587164,-1.227556,-1.371871,0.530028,-0.126205,-1.273136,-0.368948,1.075112,-0.507072,-0.919727
2,0.086405,0.003178,0.2402,0.5643,0.2432,0.048831,0.037247,0.063482,0.054186,0.055626,...,-1.416583,-0.509859,0.951067,0.987886,-0.844378,2.351052,-1.576331,0.943066,-1.217027,1.634089
3,0.057114,0.002519,0.2553,0.5261,0.2797,0.021736,0.032902,0.023896,0.002455,0.046552,...,-0.281549,-0.410451,-0.603708,-0.698567,0.318565,1.552442,0.745950,-0.425750,-0.292150,-0.219622
4,0.030365,0.001962,0.2001,0.5177,0.2455,0.031180,0.018127,0.019255,0.033654,0.000587,...,0.616316,-0.542184,-1.991939,-1.258589,-0.093435,1.226638,0.094816,1.414181,1.134098,-1.813622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.064614,0.002800,0.3117,0.5632,0.2922,0.062677,0.004353,0.055044,0.060574,0.054521,...,-0.799452,-0.125010,0.688838,-1.283586,-0.896897,-0.593720,0.601655,0.349065,-0.078235,1.095567
496,0.060358,0.002384,0.2378,0.8904,0.2529,0.046408,0.011286,0.053265,0.043462,0.056276,...,-0.783878,0.211934,0.523334,-0.946877,-0.336791,-1.316892,0.418239,0.685272,-0.057651,0.835231
497,0.052036,0.002594,0.2790,0.6497,0.3254,0.057402,0.011188,0.028405,0.032929,0.024461,...,-0.913521,-0.915024,-1.908820,-0.680418,0.019887,-0.322406,1.525265,-0.183517,0.365602,-1.653128
498,0.056991,0.002521,0.2960,0.7623,0.2392,0.028145,0.041858,0.039529,0.037737,0.038642,...,-1.283491,0.613310,0.013286,-0.518819,-1.883803,0.173149,-0.236185,0.461748,-0.635042,0.643446
499,0.053617,0.002836,0.3273,0.6512,0.2555,0.052801,0.046211,0.053749,0.045369,0.035948,...,-0.991632,-0.322668,1.582791,-0.876245,-0.751059,-1.184949,-0.174205,-0.138655,-0.410627,1.783355